/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author walke
 */
public class InformacionBiblioteca extends javax.swing.JInternalFrame {

    /**
     * Creates new form InformacionBiblioteca
     */
    public InformacionBiblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(238, 192, 107));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACION DE LA BIBLIOTECA", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bibliotecaLogo.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bibliotecaLogo2.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 260, 260));

        jTextArea1.setBackground(new java.awt.Color(255, 204, 156));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Bienvenido a BookWise:\n\nBookWize es tu biblioteca virtual, donde puedes explorar y comprar libros a \nexcelentes precios y disfrutar de descuentos especiales. \nOfrecemos una amplia variedad de títulos para satisfacer todos los gustos \ny preferencias.\n\n\nRazón Social:\n\nAccesibilidad facil hacia los libros a buen precio..\n\n\nDescripción del Proyecto:\n\nBookWise es un proyecto dedicado a proporcionar acceso fácil y asequible \na la lectura. Nuestro objetivo es fomentar el amor por los libros y hacer \nque la lectura sea accesible para todos. Para realizar este proyecto se uso \nprincipios de MVC (Modulo, Vista y Controlador), un package DAO donde esta \nla conexion hacia la base de datos del Mysql y Xampp. Este proyecto imprime\nboleta, convirtiendolas a PDF. También se genera reportes de los clientes\nregistrados, de los libros y de los trabajadores para tener un mayor control \ny orden en nuestro sistema.\n\n\nContacto:\n\nPara obtener más información, contáctanos en info@bookwize.com\nO llámanos al 944603274 para mayor atención.\n");
        jTextArea1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 153, 0)));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 560, 520));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personita.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, 70, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("© Marx BookWise");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, -1, -1));

        jPanel1.setBackground(new java.awt.Color(217, 167, 118));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(234, 207, 138)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 180));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 280, 200));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
