
package Vista;

public class Sistema_Biblioteca extends javax.swing.JFrame {
    public Sistema_Biblioteca() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jbtnFechaVenta = new javax.swing.JButton();
        jbtnGrafica = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jbtnIngresarFormAgregarLibros = new javax.swing.JButton();
        jbtnIngresarFormCliente = new javax.swing.JButton();
        jbtnIngresarFormTrabajadores = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtnFacturacion = new javax.swing.JButton();
        jbtnGestionarVenta = new javax.swing.JButton();
        jbtnCerrarSesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnInformacionBiblioteca = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jdspBiblioteca = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 240, 196));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(252, 187, 42));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VENTAS...", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnFechaVenta.setBackground(new java.awt.Color(206, 178, 47));
        jbtnFechaVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnFechaVenta.setForeground(new java.awt.Color(0, 0, 0));
        jbtnFechaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/metodo-de-pago.png"))); // NOI18N
        jbtnFechaVenta.setText("FECHA VENTA");
        jbtnFechaVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnFechaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFechaVentaActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnFechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 60));

        jbtnGrafica.setBackground(new java.awt.Color(206, 178, 47));
        jbtnGrafica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnGrafica.setForeground(new java.awt.Color(0, 0, 0));
        jbtnGrafica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestion-de-proyectos.png"))); // NOI18N
        jbtnGrafica.setText("GRAFICAR VENTAS");
        jbtnGrafica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGraficaActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 70));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 640, 230, 180));

        jPanel5.setBackground(new java.awt.Color(252, 187, 42));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("INFORMACION Y REGISTRO GENERAL DE LA BIBLIOTECA");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 60));

        jPanel6.setBackground(new java.awt.Color(252, 187, 42));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRAR...", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnIngresarFormAgregarLibros.setBackground(new java.awt.Color(206, 178, 47));
        jbtnIngresarFormAgregarLibros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnIngresarFormAgregarLibros.setForeground(new java.awt.Color(0, 0, 0));
        jbtnIngresarFormAgregarLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/formlibros.png"))); // NOI18N
        jbtnIngresarFormAgregarLibros.setText("LIBROS  ");
        jbtnIngresarFormAgregarLibros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnIngresarFormAgregarLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtnIngresarFormAgregarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarFormAgregarLibrosActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnIngresarFormAgregarLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 180, 50));

        jbtnIngresarFormCliente.setBackground(new java.awt.Color(206, 178, 47));
        jbtnIngresarFormCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnIngresarFormCliente.setForeground(new java.awt.Color(0, 0, 0));
        jbtnIngresarFormCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/formcliente.png"))); // NOI18N
        jbtnIngresarFormCliente.setText("CLIENTES  ");
        jbtnIngresarFormCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnIngresarFormCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarFormClienteActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnIngresarFormCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 50));

        jbtnIngresarFormTrabajadores.setBackground(new java.awt.Color(206, 178, 47));
        jbtnIngresarFormTrabajadores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnIngresarFormTrabajadores.setForeground(new java.awt.Color(0, 0, 0));
        jbtnIngresarFormTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/formtrabajador.png"))); // NOI18N
        jbtnIngresarFormTrabajadores.setText("TRABAJADORES  ");
        jbtnIngresarFormTrabajadores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnIngresarFormTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarFormTrabajadoresActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnIngresarFormTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, 50));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 230, 210));

        jPanel3.setBackground(new java.awt.Color(252, 187, 42));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VENTAS...", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnFacturacion.setBackground(new java.awt.Color(206, 178, 47));
        jbtnFacturacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnFacturacion.setForeground(new java.awt.Color(0, 0, 0));
        jbtnFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/metodo-de-pago.png"))); // NOI18N
        jbtnFacturacion.setText("REALIZAR VENTA");
        jbtnFacturacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFacturacionActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 60));

        jbtnGestionarVenta.setBackground(new java.awt.Color(206, 178, 47));
        jbtnGestionarVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnGestionarVenta.setForeground(new java.awt.Color(0, 0, 0));
        jbtnGestionarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestion-de-proyectos.png"))); // NOI18N
        jbtnGestionarVenta.setText("GESTIONAR VENTA");
        jbtnGestionarVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnGestionarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGestionarVentaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnGestionarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 70));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 230, 180));

        jbtnCerrarSesion.setBackground(new java.awt.Color(206, 178, 47));
        jbtnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        jbtnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apagar.png"))); // NOI18N
        jbtnCerrarSesion.setText("CERRAR SESION");
        jbtnCerrarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 810, 160, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sistemaBiblioteca.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 130, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menubiblioteca.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, 110));

        jbtnInformacionBiblioteca.setBackground(new java.awt.Color(236, 165, 75));
        jbtnInformacionBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnInformacionBiblioteca.setForeground(new java.awt.Color(0, 0, 0));
        jbtnInformacionBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        jbtnInformacionBiblioteca.setText("INFORMACION");
        jbtnInformacionBiblioteca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnInformacionBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInformacionBibliotecaActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnInformacionBiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 180, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verInfo.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 130, 110));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 920));

        jdspBiblioteca.setBackground(new java.awt.Color(245, 211, 178));
        getContentPane().add(jdspBiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 1330, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFacturacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnFacturacionActionPerformed

    private void jbtnIngresarFormAgregarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarFormAgregarLibrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnIngresarFormAgregarLibrosActionPerformed

    private void jbtnIngresarFormClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarFormClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnIngresarFormClienteActionPerformed

    private void jbtnIngresarFormTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarFormTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnIngresarFormTrabajadoresActionPerformed

    private void jbtnGestionarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGestionarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnGestionarVentaActionPerformed

    private void jbtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCerrarSesionActionPerformed

    private void jbtnInformacionBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInformacionBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnInformacionBibliotecaActionPerformed

    private void jbtnFechaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFechaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnFechaVentaActionPerformed

    private void jbtnGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGraficaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnGraficaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Sistema_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Sistema_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Sistema_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Sistema_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Sistema_Biblioteca().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JButton jbtnCerrarSesion;
    public javax.swing.JButton jbtnFacturacion;
    public javax.swing.JButton jbtnFechaVenta;
    public javax.swing.JButton jbtnGestionarVenta;
    public javax.swing.JButton jbtnGrafica;
    public javax.swing.JButton jbtnInformacionBiblioteca;
    public javax.swing.JButton jbtnIngresarFormAgregarLibros;
    public javax.swing.JButton jbtnIngresarFormCliente;
    public javax.swing.JButton jbtnIngresarFormTrabajadores;
    public javax.swing.JDesktopPane jdspBiblioteca;
    // End of variables declaration//GEN-END:variables
}
